# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            the paranoid times
tagline:          "Just like the name"
description:      "Dejan Josifović's blog|portfolio"
url:              https://theparanoidtimes.org
categories:       [projects blog]
permalink:        pretty

author:
    name:         Dejan Josifović
    mail:         www.paranoidtimes@gmail.com

plugins:
  - jekyll-sitemap

sass:
  style: compressed

# Custom vars
version:          1.2
twitter:          "@d_josifovic"
twitter-url:      https://twitter.com/d_josifovic
person-git:       "@28"
person-git-url:   https://github.com/28
proj-git:         "@theparanoidtimes"
proj-git-url:     https://github.com/theparanoidtimes
mail:             "www.paranoidtimes[at]gmail[dot]com"
pgp:              https://keys.openpgp.org/vks/v1/by-fingerprint/54477C6E6E8DCA3795500E40C99BC8906D7AF108
max-show-posts:   -1

github:
  repo:             https://github.com/theparanoidtimes/theparanoidtimes.github.io
